spring:
  config:
    import: optional:secrets.yml

  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    username: root
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  jackson:
    default-property-inclusion: non_null
